# Generated by Django 4.0.4 on 2022-12-11 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_alter_session_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionhistory',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
