# Generated by Django 4.0.4 on 2022-05-26 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_remove_user_real_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='session_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='realname',
        ),
        migrations.AddField(
            model_name='sessionhistories',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='launch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='member_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessions',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
