# Generated by Django 4.0.4 on 2022-12-11 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_alter_sessionhistory_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_attendee',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionhistory',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='checkins.session'),
        ),
    ]
