# Generated by Django 4.0.4 on 2022-11-08 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0003_rename_session_name_sessions_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionhistories',
            name='is_attendance',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='sessionhistories',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
