# Generated by Django 4.0.4 on 2022-11-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0004_sessionhistories_is_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='application_fee',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
