# Generated by Django 4.0.4 on 2022-11-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0005_sessions_application_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='application_fee',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
