# Generated by Django 4.0.4 on 2022-11-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0006_alter_sessions_application_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='SessionHistories',
            new_name='SessionHistory',
        ),
    ]
