# Generated by Django 4.0.4 on 2022-11-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0007_rename_sessions_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionhistory',
            name='is_supporter_car',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='is_supporter_dj',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='is_supporter_welcome',
            field=models.BooleanField(default=0),
        ),
    ]
